import { readFile, mkdir, writeFile, rename, rm } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import nextEnv from "@next/env";
import openapiTS, { astToString } from "openapi-typescript";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
nextEnv.loadEnvConfig(root);
const output = resolve(root, "src/types/generated/api.ts");
const snapshot = resolve(root, "openapi/schema.json");
const local = process.argv.includes("--local");

async function main() {
  let schema;
  if (local) {
    schema = JSON.parse(await readFile(snapshot, "utf8"));
  } else {
    const url =
      process.env.OPENAPI_SCHEMA_URL || "http://localhost:3000/docs-json";
    const response = await fetch(url, { signal: AbortSignal.timeout(15000) });
    if (!response.ok) throw new Error("Swagger trả HTTP " + response.status);
    schema = await response.json();
  }
  if (
    !schema.openapi?.startsWith("3.") ||
    !schema.paths ||
    !schema.components?.schemas
  ) {
    throw new Error(
      "Cần OpenAPI 3 JSON chứa paths và components.schemas; /docs là giao diện HTML.",
    );
  }
  const ast = await openapiTS(schema, { alphabetize: true });
  const source =
    "/** Generated by npm run api:generate. DO NOT EDIT. */\n" +
    astToString(ast);
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output + ".tmp", source);
  await rename(output + ".tmp", output);
  if (!local) {
    await mkdir(dirname(snapshot), { recursive: true });
    await writeFile(snapshot + ".tmp", JSON.stringify(schema, null, 2) + "\n");
    await rename(snapshot + ".tmp", snapshot);
  }
  console.log(
    "Generated API types from " +
      (local ? "local snapshot" : "Swagger HTTP endpoint") +
      ".",
  );
}
main().catch(async (error) => {
  await rm(output + ".tmp", { force: true });
  console.error("Không thể đồng bộ DTO: " + error.message);
  console.error(
    "Kiểm tra backend /docs-json và OPENAPI_SCHEMA_URL. Dùng npm run api:generate:local để tái tạo từ snapshot đã lưu.",
  );
  process.exitCode = 1;
});
